#!/usr/bin/env bash
#Install and configure HAproxy

apt-get update
apt-get install -y haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 54.91.158.200:80 check
    server web-02 54.88.203.92:80 check
EOT

# Update the hostname
sudo hostnamectl set-hostname 485026075-haproxy

# Enable HAProxy as a service managed by the init script
sudo service haproxy enable 

# Restart HAProxy service
sudo service haproxy restart
