#!/usr/bin/env bash
# installs the reverse proxy - Nginx
sudo apt update && upgrade
sudo apt install nginx -y 
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
curl -sS http://localhost/ | grep -q "Holberton School" && echo "Test Passed" || echo "Test Failed"
sudo service nginx start
