#!/usr/bin/env bash
#Update system packages
sudo apt update

# Install the nginx web server
sudo apt-get install -y nginx
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "53i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart 
