#!/usr/bin/env bash
#Update system packages
sudo apt update

# Install nginx web server
sudo apt install -y nginx

# Configure nginx for redirection
sudo bash -c `cat > /etc/nginx/conf.d/redirect_me.config <<EOL
server {
	listen 80;
	server_name sabirwalid.com;

	location /redirect_me {
		return 301 https://youtube.com;
	}

	location / {
		#My main website configuration goes here
		#Add more "location" blocks if needed
	}
    }
    EOL`

# Verify nginx configuration and restart the server
sudo nginx -t && sudo systemctl restart nginx
